### ISSUE TITLE
Mangles `Content-Type` header

### ISSUE THREAD

**Issue by milgner** [3scale/webhook_multiplexer#2]
## Reproduction

- start a fake webserver, i.e. with Netcat: `nc -l -p 8080 localhost`
- start a multiplexer `WEBHOOK_MULTIPLEXER_URLS="http://localhost:8080" rackup`
- run a cURL request: `curl -v -H "Content-Type: application/json" -X POST -d '{ "foo": "bar" }' http://localhost:9292/webhook`

## Expected behaviour

The server sees `Content-Type: application/json`

## Observed behaviour

The header is `Content-Type: application/x-www-form-urlencoded`.

**Comment by mikz** [comment]
Indeed. Confirmed. You can also start it with `DEBUG=1` to see exactly what it sends over the wire.

**Comment by mikz** [comment]
@milgner thanks for thorough report. Hope it works for you now!

**Comment by milgner** [comment]
Thanks a lot for the quick response! I had planned to look into it more closely over the weekend, will give it a try!
